config/routes.rb
Rails.application.routes.draw do

  root to: 'monsters#index'

  devise_for :users

  resources :monsters do
    resources :bookings, only: [:new, :create]
  end

  get '/dashboard', to: 'pages#dashboard', as: :dashboard

  resources :bookings,only: [:update, :destroy, :show] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  has_one :review
  belongs_to :monster
  validates :start_date, presence: true
  validates :end_date, presence: true
  after_validation :set_total_price

  def set_total_price
    self.total_price = (end_date - start_date).to_i * monster.price
  end
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo
  validates :name, presence: true
  validates :description, length: { maximum: 100 }, presence: true
  validates :price, presence: true


    include PgSearch::Model
  pg_search_scope :search_by_monster_characteristic,
    against: [ :name, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
    def avarage_rating
      if reviews.length > 0
      self.reviews.pluck(:rating).sum / reviews.length
      else
      "No review"
      end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :booking
    validates :content, :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @monster = Monster.find(params[:monster_id])
    @booking = Booking.new(booking_params)
    @booking.monster = @monster
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@monster, @booking)
    else
      render new
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @monster = Monster.find(params[:monster_id])
    @booking = Booking.new
  end

  def show
    make_booking
    @monster = Monster.find(params[:id])
    @booking.monster = @monster
  end

  def update
    make_booking
    @booking.save!
    redirect_to booking_path(@booking)
  end

  def destroy
    make_booking
    @booking.destroy
    redirect_to root_path
  end

  private

  def booking_params
    params.require(:booking).permit(:monster_id, :user_id, :start_date, :end_date, :total_price)
  end

  def make_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @monsters = Monster.search_by_monster_characteristic(params[:query])
    else
      @monsters = Monster.all
    end
  end

  def new
    @monster = Monster.new
  end

  def show; end

  def create
    @monster = Monster.new(monster_params)
    @monster.user = current_user

    if @monster.save
      redirect_to monsters_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @monster.update(monster_params)
    redirect_to monster_path(@monster)
  end

  def destroy
    @monster.destroy
    redirect_to monsters_path
  end

  private

  def monster_params
    params.require(:monster).permit(:name, :description, :price, :photo)
  end

  def set_monster
    @monster = Monster.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @monsters = Monster.where(user_id: current_user.id)
    @completed_bookings = current_user.bookings.where("end_date < '#{Date.today}'")
    @future_bookings = current_user.bookings.where("start_date >= '#{Date.today}'")
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_booking, only: [:new, :create]
  def index
    @reviews = Review.all
  end

  # def show
  #   find_review
  # end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  # def edit
  #   find_review
  # end

  # def update
  # end
  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to dashboard_path
  end

  private

  def find_monster
    @monster = Monster.find(params[:monster_id])
  end

  def review_params
     params.require(:review).permit(:content, :rating, :booking_id)
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_card.html.erb
 <% if booking.monster.photo.attached? %>
   <div class="booking-card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('#')">
    <div class="row" style="text-align: center; margin: 10px 5px">
      <div class="col">
       <h6>
         <%= link_to booking.monster.name, monster_path(booking.monster), class: 'text-white booking-card-name' %>
       </h6>
       <p>Your booking details:</p>
       <p> From: <%= booking.start_date %></p>
       <p> To: <%= booking.end_date %></p>
       <p> Total: <%= booking.total_price %> $</p>

       <% if @future_bookings.include?(booking)  %>

        <p></p>

       <% elsif @completed_bookings.include?(booking) && booking.review.nil? %>

       <p><%= link_to 'Leave a review', new_booking_review_path(booking), class: 'text-white booking-card-name' %></p>
       <% else %>
       <p> Your rating: <%=booking.review.rating%></p>
       <p><%= link_to "Read your review", "#" %></p>
        <% end %>

     </div>
    </div>
  </div>


<% else %>
    <div class="booking-card"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('#')">
    <div class="row" style="text-align: center; margin: 10px 5px">
      <div class="col">
       <h6>
         <%= link_to booking.monster.name, monster_path(booking.monster), class: 'text-white booking-card-name' %>
       </h6>
       <p>Your booking details:</p>
       <p> From: <%= booking.start_date %></p>
       <p> To: <%= booking.end_date %></p>
       <p> Total: <%= booking.total_price %> $</p>

       <% if @future_bookings.include?(booking)  %>
        <p>hello</p>
       <% elsif @completed_bookings.include?(booking) && booking.review.nil? %>
       <p><%= link_to 'Leave a review', '#', class: 'text-white booking-card-name' %></p>
       <% else %>
       <p> Your rating: <%=booking.review.rating%></p>
       <p><%= link_to "Read your review", "#" %></p>
        <% end %>


     </div>
    </div>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<div class="container d-flex justify-content-center align-items-center h-50">
  <div class="row w-40">
    <div class="col">
      <%= simple_form_for [@monster, @booking] do |f| %>
      <%= f.input :start_date, as: :date, input_html: { class: 'datepicker' }, html5: true, start_day: Date.today.day %>
      <%= f.input :end_date, as: :date, input_html: { class: 'datepicker' }, html5: true, start_day: Date.today.day %>
      <%= f.submit "Confirm booking", class: "btn btn-success" %>
      <%= link_to "Back to monsters", monsters_path, class: "btn btn-warning" %>
    </div>
  </div>
</div>
<% end %>

app/views/bookings/create.html.erb
<div class="container">
 <div class="row justify-content-center">
   <div class="col-6">
    <h1>Make a booking</h1>
    <%= simple_form_for [@monster, @booking] do |f| %>
    <%= f.input :start_date, as: :date %>
    <%= f.input :end_date, as: :date %>
    <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
    <%= f.submit "Book This Monster", class: 'btn btn-primary' %>
  <% end %>
    </div>
  </div>
</div>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<div class="booking-form-bg">
  <div class="booking-form-left">
    <div class="card" id="booking-form">
      <%= render "form" %>
    </div>
  </div>
  <div class="booking-form-txt">
    <h2> Book <%= @monster.name %></h2>
    <p>Thank you for choosing <%= @monster.name %>!<br>Select your start and end date to book your monster for all your monster needs </p>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container" style="text-align: center; width: 500px; margin-top: 50px;
">
  <div style="margin:50px;">
  <i class="far fa-check-circle fa-3x" style="color:green;"></i>
  <h2> Thanks for booking  </h2><br>
  <h1><%= @monster.name %><h1>
    <%= cl_image_tag @monster.photo.key, height: 300, width: 400, crop: :fill %>
</div>
    <div style="text-align: left; margin:50px">
    <p>Your booking details:</p>
     <i class="fas fa-calendar-check" style="color:green;"></i><strong>  From</strong> <%= @booking.start_date %>
     <strong>To</strong> <%= @booking.end_date %><br>
    <i class="fas fa-dollar-sign" style="color:green;"></i><strong>   Total:</strong> $
      <%= @monster.price * ((@booking.end_date - @booking.start_date).to_i) %>
    </div>


    <%= link_to "Back", monsters_path %>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MonsterRental</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
  <%= render 'components/nav' %>
  <%= render 'shared/flashes' %>
 <%= yield %>
</body>
</html>

app/views/monsters/_card.html.erb
<% if monster.photo.attached? %>
<div class="monster-card"style="text-align: center; margin: 10px 5px;">
  <div style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path monster.photo.key, height: 300, width: 400, crop: :fit %>'); display: flex; align-items: center; flex-grow: 1; margin-bottom: 8px;">
    <h2>
      <%= link_to monster.name, monster_path(monster), class: 'monster-card-name' %>
    </h2>
  </div>

  <div class="card-links">
   <%= link_to "Edit", edit_monster_path(monster),class: "btn btn-ghost"%>
   <%= link_to "Delete", monster_path(monster), class: "btn btn-ghost", method: :delete, data: { confirm: "Are you sure?" } %>
 </div>
 <!-- End of Card -->
</div>

<% else %>
<div class="monster-card" style="text-align: center; margin: 10px 5px"
style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('#')">
<h1>
  <%= link_to monster.name, monster_path(monster), class: 'text-white monster-card-name' %>
</h1>
<div class="card-links">
 <%= link_to "Edit", edit_monster_path(monster),class: "btn btn-ghost"%>
 <%= link_to "Delete", monster_path(monster), class: "btn btn-ghost", method: :delete, data: { confirm: "Are you sure?" } %>
</div>
<!-- End of Card -->
</div>
<% end %>

app/views/monsters/_form.html.erb
<div class="container d-flex justify-content-center align-items-center h-50">
  <div class="row w-60">
    <div class="col">
      <h1 class="text-center">Monster Details</h1>
      <%= simple_form_for @monster do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :description, label: "Describe Your Monster" %>
      <%= f.input :photo, as: :file %>
      <%= link_to 'Cancel', root_path, class: 'text-warning mr-2' %>
      <%= f.submit "Confirm", class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/monsters/destroy.html.erb
<h1>Monsters#destroy</h1>
<p>Find me in app/views/monsters/destroy.html.erb</p>

app/views/monsters/edit.html.erb
<div class="booking-form-bg">
  <div class="booking-form-left">
    <div class="card" id="add-monster-form">
      <%= render "form" %>
    </div>
  </div>
  <div class="booking-form-txt">
    <h2>Edit Your Monster</h2>
    <p>Things change, we know!<br>Monsters grow up and become their own monster and have monsters of their own.<br>Change their details here</p>
  </div>
</div>

app/views/monsters/index.html.erb
<div class="homepage homepage-bg">
  <div>
   <svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="width: 0;height: 0;">
    <defs>
      <filter id="goo">
        <feGaussianBlur in="SourceGraphic" stdDeviation="4" result="blur" />
        <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
        <feBlend in="SourceGraphic" in2="goo" />
      </filter>
    </defs>
  </svg>

  <h1 class="title" style="color: #3FEF1F;">
    Monster Rentals
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
    <span class="drop"></span>
  </h1>
</div>

<!--   <h1>Monster Rentals</h1>
  <p>For all your Monster needs</p> -->

  <div class="d-flex w-75 justify-content-center">
    <div class="w-50 mr-3">
      <%= form_tag monsters_path, method: :get do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control input-style",
      placeholder: "Enter monster name..."
      %>
    </div>
    <div>
      <%= submit_tag "Search", class: "btn btn-primary search-btn" %>
    </div>
    <% end %>
  </div>
</div>

<div class="popular-section">
  <div class="container">
    <div class="row p-3">
      <div class="col">
        <h2 class="subtitle">Most popular</h2>
        <h5 class="subtitle-description">Everyones favourite monsters</h5>
      </div>
    </div>
    <div class="row">

      <div class="monster-cards-container col-md-6">
        <div class="big-monster-card">
          <% first_monster = @monsters.first %>
          <% if first_monster.photo.attached? %>
          <div class="first-monster-card background-image-style"
          style="background-image: url('<%= cl_image_path first_monster.photo.key, height: 300, width: 400, crop: :fit %>')">
          <!-- End of Card -->
        </div>
        <p>
          <%= link_to first_monster.name, monster_path(first_monster), class: 'text-white monster-card-name' %>
        </p>
        <% end %>
      </div>
    </div>

    <div class="small-monster-cards col-md-6">
      <% @monsters.drop(1)[0..3].each do |monster| %>
      <div class="col-md-6">
        <% if monster.photo.attached? %>
        <div class="monster-card background-image-style"
        style="background-image: url('<%= cl_image_path monster.photo.key, height: 300, width: 400, crop: :fit %>')">
        <!-- End of Card -->
      </div>
      <p>
        <%= link_to monster.name, monster_path(monster), class: 'text-white monster-card-name' %>
      </p>
      <% end %>
    </div>
    <% end %>
  </div>


</div>

</div>
</div>

app/views/monsters/new.html.erb
<div class="booking-form-bg">
  <div class="booking-form-left">
    <div class="card" id="add-monster-form">
      <%= render "form" %>
    </div>
  </div>
  <div class="booking-form-txt">
    <h2>Add Your Monster</h2>
    <p>Fill out the details of your monster so everyone can fulfill their monster needs</p>
  </div>
</div>

app/views/monsters/show.html.erb
<div class="card-monster" style="text-align: center;margin:0 auto; width: 500px;  margin-top: 50px; background-color: #f1ebf5;">

  <div class="image" style="margin:0 ; background-color :rgba(255,255,255,0.7); background-blend-mode:lighten; background-image: url('<%= cl_image_path @monster.photo.key, height: 300, width: 400, crop: :fit %>')"><%= cl_image_tag @monster.photo.key, height: 300, width: 300, crop: :fill %>

  </div>
   <h2 style="text-align:right; color:#6930c3; margin-right: 30px;">
    <% if @monster.reviews.length.positive? %>
    ★
    <% end %>
    <%= @monster.avarage_rating %></h2>

  <div class="card-monster-infos" style="margin-top:10px; margin-bottom: 50px;">
    <div>

      <h2 style="text-align: center;"><%=@monster.name %></h2>
      <p><%=@monster.description%></p>
    </div>
    <h2 class="card-monster-pricing">$<%= @monster.price %></h2>
  </div>

  <div class="d-flex justify-content-between ml-2">
    <i class="fas fa-arrow-left"><%= link_to "Back", monsters_path %></i>

     <%= link_to "Book monster", new_monster_booking_path(@monster), class: "btn btn-success", style:"border-radius:25px;"%>
     <div></div>

</div>
    <div class="show-review" style="text-align: left; margin:20px;">
      <% if @monster.reviews.length.positive? %>
      <i class="fas fa-comment" style="color:#1a508b;">  Reviews</i>
      <% end %>

        <% @monster.reviews.each do |review|%>
           <div class="card" style="border-color: #719fb0; padding:10px; border-radius:10px;">
         <p>★<%= review.rating %>
          <%= review.content %>
         </p>

        </div>
         <% end %>

    </div>
</div>

app/views/pages/dashboard.html.erb
 <div class="d-flex justify-content-center" style = "margin-top: -50px">
     <div class="d-flex flex-column align-items-center">
     <div class="nav-item dropdown">
          <%= image_tag "https://i.pravatar.cc/300", class: "avatar dropdown-toggle image-dashboard", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
        <h1> Hello <%=current_user.username%> </h1>
        </div>
  </div>

<div class="container-fluid dashboard-container py-5">
  <div class="row">

   <div class="col-md-2">
    <div class="card p-2">
      <div class="dashboard-infos">
        <div class="col">
          <%= link_to "Monsters", dashboard_path(:anchor => "my-monsters"), class: "button-dashboard" %>
        </div>
        <div class="col">
          <%= link_to "Past Bookings", dashboard_path(:anchor => "past-bookings"), class: "button-dashboard"%>
        </div>
        <div class="col">
          <%= link_to "Upcoming Bookings", dashboard_path(:anchor => "upcoming-bookings"), class: "button-dashboard"%>
        </div>
        <div class="col">
          <%= link_to "Reviews", dashboard_path(:anchor => "#") ,class: "button-dashboard"%>
        </div>
      </div>
    </div>
   </div>

 <div class="col-md-5">
  <div class="card p-4">
    <div class="d-flex justify-content-between align-items-center">
    <h1 class ="text-center">Your Monsters</h1>
        <span class="nav-link btn btn-add-monster"><%= link_to 'Add Monster', new_monster_path, class: 'text-white' %></span>
    </div>
    <div class="row">
     <% @monsters.each do |monster| %>
       <div class="col-6 p-2">
        <%= render 'monsters/card', monster: monster %>
      </div>
     <% end %>
    </div>
  </div>
 </div>

 <div class="col-md-5">
<div class="card p-4 ">
    <h1> Completed bookings</h1>
    <div class="row p-2" style="margin: 0px">
      <% @completed_bookings.each do |booking| %>
        <div class="col-6 p-0">
          <%= render 'bookings/card', booking: booking %>
        </div>
      <% end %>
    </div>
  </div>

<div class="card p-4">
    <h1> Future bookings</h1>
    <div class="row p-2" style="margin: 0px">
      <% @future_bookings.each do |booking| %>
        <div class="col-6 p-0">
          <%= render 'bookings/card', booking: booking %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<div class="homepage homepage-bg">
</div>

app/views/reviews/new.html.erb
<div class="container" style="width: 500px;">
  <h1>Your review</h1>
  <%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating, collection: (0..5) %>
  <%= f.input :content, label: "How was your monster?"%>
  <%= link_to 'Cancel', root_path, class: 'text-danger mr-2' %>
  <%= f.submit "Confirm", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>